pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - beta
pr: none

steps:
- checkout: self
  persistCredentials: true
  clean: true
- script: 'dotnet publish $(Build.SourcesDirectory)/MusicPlayer.Wasm/MusicPlayer.Wasm.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary -c Release'
  displayName: 'Build'
- script: |
      echo "Copy built files ..."
      mkdir $(Build.SourcesDirectory)/MusicPlayer.Wasm.Beta
      cp -r $(Build.SourcesDirectory)/MusicPlayer.Wasm/bin/Release/netstandard2.0/publish/* $(Build.SourcesDirectory)/MusicPlayer.Wasm.Beta
      cd $(Build.SourcesDirectory)/MusicPlayer.Wasm.Beta

      echo "Initialize git ..."
      git --version
      git init
      git remote add origin https://github.com/rh-utensils/MusicPlayer.Wasm.Beta.git
      git remote set-url origin https://hampoelz:$(git-token)@github.com/rh-utensils/MusicPlayer.Wasm.Beta.git
      echo "Download external files ..."
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer/beta/LICENSE"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer/rewrite/MusicPlayer.Wasm/workbox.js"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm.Beta/master/CNAME"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm.Beta/master/manifest.json"
      echo "Commit new files ..."
      git add *
      git config user.email "bot@hampoelz.net"
      git config user.name "HampisBot"
      git commit -m "[DevOps Pipeline] Automated beta build ($(build.buildNumber)) from $(date +"%D")"
      echo "Push files to repository ..."
      git push -f origin master
  displayName: 'Publish'