pool:
  vmImage: 'ubuntu-latest'

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - VSCode/WinUI-Update

steps:
- checkout: self
  persistCredentials: true
  clean: true
- script: 'dotnet publish $(Build.SourcesDirectory)/MusicPlayer.Wasm/MusicPlayer.Wasm.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary -c Release'
  displayName: 'Build'
- script: |
      echo "Copy built files ..."
      mkdir $(Build.SourcesDirectory)/MusicPlayer.Wasm.Nightly
      cp -r $(Build.SourcesDirectory)/MusicPlayer.Wasm/bin/Release/netstandard2.0/publish/* $(Build.SourcesDirectory)/MusicPlayer.Wasm.Nightly
      cd $(Build.SourcesDirectory)/MusicPlayer.Wasm.Nightly

      echo "Initialize git ..."
      git --version
      git init
      git remote add origin https://github.com/rh-utensils/MusicPlayer.Wasm.Nightly.git
      git remote set-url origin https://hampoelz:$(git-token)@github.com/rh-utensils/MusicPlayer.Wasm.Nightly.git
      echo "Download external files ..."
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm/master/LICENSE"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm.Nightly/master/CNAME"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm.Nightly/master/manifest.json"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm.Nightly/master/.htaccess"
      wget "https://raw.githubusercontent.com/rh-utensils/MusicPlayer.Wasm.Nightly/master/workbox.js"
      echo "Commit new files ..."
      git add *
      git config user.email "bot@hampoelz.net"
      git config user.name "HampisBot"
      git commit -m "[DevOps Pipeline] Automated nightly build ($(build.buildNumber)) from $(date +"%D")"
      echo "Push files to repository ..."
      git push -f origin master
  displayName: 'Publish'